name: efficientnet_b2b-mask_rcnn-576x576
domain: Instance Segmentation
problem: Custom Instance Segmentation
framework: OTEDetection v2.9.1
summary: Custom instance segmentation based on Mask R-CNN architecture with EfficientNet-b2.
annotation_format: COCO
initial_weights: snapshot.pth
dependencies:
- sha256: b00407a212bdba77866b6c337a24e997b4b2621afb50e62b261df1a4f8efd3c6
  size: 53452621
  source: https://storage.openvinotoolkit.org/repositories/openvino_training_extensions/models/instance_segmentation/v2/efficientnet_b2b-mask_rcnn-576x576.pth
  destination: snapshot.pth
- source: ../../../../../ote/tools/train.py
  destination: train.py
- source: ../../../../../ote/tools/eval.py
  destination: eval.py
- source: ../../../../../ote/tools/export.py
  destination: export.py
- source: ../../../../../ote/tools/compress.py
  destination: compress.py
- source: ../../../../../ote
  destination: packages/ote
- source: ../../requirements.txt
  destination: requirements.txt
max_nodes: 1
training_target:
- GPU
inference_target:
- CPU
hyper_parameters:
  basic:
    batch_size: 8
    base_learning_rate: 0.025
    epochs: 12
  extra:
    custom_classes:
      name: Custom classes
      param: --classes
      type: string
      default: ''
output_format:
  onnx:
    default: true
  openvino:
    default: true
    input_format: BGR
optimisations: ~
metrics:
- display_name: Bbox AP @ [IoU=0.50:0.95]
  key: ap
  unit: '%'
  value: 35.2
- display_name: Segm AP @ [IoU=0.50:0.95]
  key: ap
  unit: '%'
  value: 31.0
- display_name: Size
  key: size
  unit: Mp
  value: 13.27
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 26.92
gpu_num: 1
config: model.py
tensorboard: true
