backbone_config:
  arch: resnext50_32x4d
  disable_layer_3: true
  disable_layer_4: true
head:
  type: AttentionBasedLSTM
model_path: model_checkpoints/medium_photographed_0185.pth
model_url: https://download.01.org/opencv/openvino_training_extensions/models/formula_recognition/medium_photograped_0185.pth
device: cuda
vocab_path: vocabs/vocab_medium.json
val_transforms_list:
  - name: "TransformRescale"
    scale_min: 1.5
    scale_max: 1.5
  - name: TransformCropPad
    target_shape:
      - 160
      - 1400
train:
  batch_size: 4
  learning_rate: 0.000001
  log_path: logs
  optimizer: Adam
  save_dir: model_checkpoints
  datasets:
    train:
      - type: Im2LatexDataset
        data_path: ../../../data/formula_recognition/sample_medium_dataset
        annotation_file: train_filter.lst
    validate:
      - type: Im2LatexDataset
        data_path: ../../../data/formula_recognition/sample_medium_dataset
        annotation_file: validate_filter.lst
  train_transforms_list:
  - name: "TransformRescale"
    scale_min: 1.5
    scale_max: 1.5
eval:
  dataset:
    type: Im2LatexDataset
    data_path: ../../../data/formula_recognition/sample_medium_dataset
    annotation_file: validate_filter.lst
  render: false
demo:
  transforms_list: []
export:
  res_encoder_name: medium_v2_encoder.onnx
  res_decoder_name: medium_v2_decoder.onnx
  encoder_input_names: 'imgs'
  encoder_output_names: 'row_enc_out,hidden,context,init_0'
  decoder_input_names: 'dec_st_h,dec_st_c,output_prev,row_enc_out,tgt'
  decoder_output_names: 'dec_st_h_t,dec_st_c_t,output,logit'
  export_ir: true
  verbose_export: false
  input_shape_encoder:
    - 1
    - 3
    - 160
    - 1400
  decoder_input_shapes:
    - [1, 512]
    - [1, 512]
    - [1, 256]
    - [1, 20, 175, 512]
    - [1, 1]

