name: s3d-rgb-mobilenet-v3-stream-csl
domain: Action Recognition
problem: Gesture Recognition
framework: OTEAction v0.6.0
summary: Common Sign Language (CSL) Recognition based on S3D-MobileNet-V3.
annotation_format: CustomAction
initial_weights: snapshot.pth
dependencies:
- sha256: 9b7523592f0993065cb251bb159f3528b619a6f7906773a1f2a43a4b74b55b7b
  size: 33203577
  source: https://storage.openvinotoolkit.org/repositories/openvino_training_extensions/models/common_sign_language/s3d-mobilenetv3-large-common_sign_language.pth
  destination: snapshot.pth
- source: ../../../../../ote/tools/train.py
  destination: train.py
- source: ../../../../../ote/tools/eval.py
  destination: eval.py
- source: ../../../../../ote/tools/export.py
  destination: export.py
- source: ../../../../../ote/tools/compress.py
  destination: compress.py
- source: ../../../../../ote
  destination: packages/ote
- source: ../../requirements.txt
  destination: requirements.txt
- source: ../tools
  destination: tools
max_nodes: 1
training_target:
- GPU
inference_target:
- CPU
- iGPU
hyper_parameters:
  basic:
    batch_size: 12
    base_learning_rate: 0.002
    epochs: 65
output_format:
  onnx:
    default: true
  openvino:
    default: true
    input_format: RGB
optimisations: ~
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 4.113
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 4.227
- display_name: Top-1 accuracy
  key: accuracy
  unit: '%'
  value: 98.0
gpu_num: 2
tensorboard: true
config: model.py
