name: face-detection-0205
domain: Object Detection
problem: Face Detection
framework: OTEDetection v2.9.1
summary: Face Detection based on MobileNetV2 (FCOS).
annotation_format: COCO
initial_weights: snapshot.pth
dependencies:
- sha256: 9bba40206d0839993dbdee2a41d8622a717da7f3168a6d2d19ec1e9f15c63fa1
  size: 16413291
  source: https://storage.openvinotoolkit.org/repositories/openvino_training_extensions/models/object_detection/v2/face-detection-0205-retrained.pth
  destination: snapshot.pth
- source: ../../../../../ote/tools/train.py
  destination: train.py
- source: ../../../../../ote/tools/eval.py
  destination: eval.py
- source: ../../../../../ote/tools/export.py
  destination: export.py
- source: ../../../../../ote/tools/compress.py
  destination: compress.py
- source: ../../../../../ote
  destination: packages/ote
- source: ../../requirements.txt
  destination: requirements.txt
dataset_requirements:
  classes:
  - face
max_nodes: 1
training_target:
- GPU
inference_target:
- CPU
- iGPU
hyper_parameters:
  basic:
    batch_size: 32
    base_learning_rate: 0.05
    epochs: 70
output_format:
  onnx:
    default: true
  openvino:
    default: true
    input_format: BGR
optimisations:
  nncf_quantization:
    config: compression_config.json
    default: false
  nncf_pruning:
    config: compression_config.json
    default: false
metrics:
- display_name: AP @ [IoU=0.50:0.95]
  key: bbox
  unit: '%'
  value: 22.7
- display_name: AP for faces > 64x64
  key: ap_64x64
  unit: '%'
  value: 93.995
- display_name: WiderFace Easy
  key: widerface_e
  unit: '%'
  value: 92.606
- display_name: WiderFace Medium
  key: widerface_m
  unit: '%'
  value: 87.556
- display_name: WiderFace Hard
  key: widerface_h
  unit: '%'
  value: 56.221
- display_name: Size
  key: size
  unit: Mp
  value: 2.02
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 2.94
gpu_num: 3
tensorboard: true
config: model.py
