name: x3d-rgb-mobilenet-v3-lgd-gc
domain: Action Recognition
problem: Custom Action Recognition
framework: OTEAction v0.6.0
summary: Custom Action Recognition based on X3D-MobileNet-V3-LGD-GC.
annotation_format: CustomAction
initial_weights: snapshot.pth
dependencies:
- sha256: 37ff91f3658d0c4489e9a3043d872bd4b19dec67e2fda453e73ac2d200726e5d
  size: 47881016
  source: https://storage.openvinotoolkit.org/repositories/openvino_training_extensions/models/custom_action_recognition/x3d-mobilenetv3-large-kinetics700-youtube8msegments-fixed.pth
  destination: snapshot.pth
- source: ../../../../../ote/tools/train.py
  destination: train.py
- source: ../../../../../ote/tools/eval.py
  destination: eval.py
- source: ../../../../../ote/tools/export.py
  destination: export.py
- source: ../../../../../ote/tools/compress.py
  destination: compress.py
- source: ../../../../../ote
  destination: packages/ote
- source: ../../requirements.txt
  destination: requirements.txt
- source: ../tools
  destination: tools
max_nodes: 1
training_target:
- GPU
inference_target:
- CPU
- iGPU
hyper_parameters:
  basic:
    batch_size: 12
    base_learning_rate: 0.001
    epochs: 65
output_format:
  onnx:
    default: true
  openvino:
    default: true
    input_format: RGB
optimisations: ~
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 4.472
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 4.74
- display_name: UCF-101 Mean Top-1 accuracy
  key: accuracy
  unit: '%'
  value: 93.63
gpu_num: 2
tensorboard: true
config: model.py
