lr_finder:
  enable: True
  mode: TPE
  stop_after: False
  num_epochs: 6
  step: 0.001
  smooth_f: 0.01
  epochs_warmup: 1
  path_to_savefig: 'lr_finder.jpg'
  max_lr: 0.01
  min_lr: 0.001
  n_trials: 15

model:
  name: 'efficientnet_b0'
  type: 'classification'
  pretrained: True
  save_chkpt: True
  feature_dim: 1280

custom_datasets:
  roots: ['path/to/train_folder', 'path/to/val_folder']
  types: ['classification_image_folder', 'classification_image_folder']
  names: ['data_train', 'data_val']

data:
  root: './'
  sources: ['data_train']
  targets: ['data_val']
  height: 224
  width: 224
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]
  save_dir: 'path/to/output_dir'
  workers: 6
  transforms:
    random_flip:
      enable: True
      p: 0.5
    random_rotate:
      enable: True
      p: 0.35
      angle: (-10,10)
    augmix:
      enable: True
      cfg_str: "augmix-m5-w3"

loss:
  name: 'am_softmax'
  softmax:
    compute_s: True

sampler:
  train_sampler: 'RandomSampler'

metric_losses:
  enable: False

train:
  optim: 'sam'
  lr: 0.003
  nbd: True
  max_epoch: 200
  weight_decay: 5e-4
  batch_size: 84
  fixbase_epoch: 0
  lr_scheduler: 'warmup'
  warmup: 5
  base_scheduler: 'reduce_on_plateau'
  early_stoping: True
  train_patience: 5
  lr_decay_factor: 200
  deterministic: True
  patience: 5
  gamma: 0.1
  ema:
    enable: True
    ema_decay: 0.999

sam:
  enable: True
  rho: 0.05

test:
  batch_size: 128
  evaluate: False
  eval_freq: 1